services:
  db:
    container_name: wanted_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wanted
    ports:
      - "35432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    container_name: wanted_redis
    image: redis:7.4.2
    ports:
      - "16379:6379"
    restart: always