spring:
  datasource:
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_NAME}?currentSchema=${SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${SECRET_KEY}