spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true
        highlight_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: dev
    password: 1234
    driver-class-name: org.postgresql.Driver


#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace