spring:
  application:
    name: wanted-shop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sandro
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace  # 파라미터 바인딩 로그