version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cqrs-challenge
    volumes:
      - ./postgres-data:/var/lib/postgresql/data