spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/preonboarding
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  defer-datasource-initialization: true
