spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: 1234
    url: jdbc:postgresql://localhost:5432/db_commerce
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace